# Generated by Django 4.2.4 on 2023-08-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=20)),
                ('entidad', models.PositiveIntegerField()),
            ],
        ),
    ]
