# Generated by Django 4.2.4 on 2023-08-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentdata',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterField(
            model_name='documentdata',
            name='entidad',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='documentdata',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
    ]
