# Generated by Django 4.2.4 on 2023-08-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_documentdata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdata',
            name='archivo_zip',
            field=models.FileField(blank=True, null=True, upload_to='generated_zips/'),
        ),
    ]
