# Generated by Django 4.2.4 on 2023-08-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_documentdata_archivo_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdata',
            name='archivo_zip',
            field=models.FileField(blank=True, null=True, upload_to='generated_zips'),
        ),
    ]
