# Generated by Django 4.2.4 on 2023-08-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_documentdata_archivo_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentdata',
            name='archivo_zip',
        ),
        migrations.AddField(
            model_name='documentdata',
            name='archivo_docx',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='documentdata',
            name='archivo_texto',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
